server:
    port: 8080

spring:
    application: 
        name: projetoloja
    datasource:
        url: jdbc:postgresql://dpg-ct1pjil6l47c73bhp3n0-a.oregon-postgres.render.com:5432/crudloja
        username: crudloja_user
        password: 1oQRp1VNvZZTGKGVQuIOygiKPECERUru
        driver-class-name: org.postgresql.Driver
        initialize: true

jpa:
    hibernate:
        ddl-auto: update
        generate-ddl: true

sql:
    init:
        schema-locations: classpath:/schema-postgresql.sql
        mode: always
        platform: postgres