server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-ct1paie8ii6s73fi5t00-a.oregon-postgres.render.com:5432/projetoloja
        username: projetoloja_y3t8_user
        password: zADCP0gaC7a7TswBRUv2srMuZgzCF4cM
        driver-class-name: org.postgresql.Driver
        initialize: true

jpa:
    hibernate:
        ddl-auto: update
        generate-ddl: true

sql:
    init:
        schema-locations: classpath:/schema-postgresql.sql
        mode: always
        platform: postgres