server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cstjtrggph6c739fgm70-a.oregon-postgres.render.com:5432/projetoloja
        username: banco_uoyu_user
        password: M9O9anqbXrgfSisgC65AipdLoyh4bYmr
        driver-class-name: org.postgresql.Driver
        initialize: true

jpa:
    hibernate:
        ddl-auto: create-drop
        generate-ddl: true

sql:
    init:
        schema-locations: classpath:/schema-postgresql.sql
        mode: always
        platform: postgres